### ISSUE TITLE
Can't use package in windows wsl

### ISSUE THREAD

**Issue by Lanayx** [tensorflow/probability#1717]
Hi, I'm trying to use capsa package which has dependency on ternsoflow-probability and I'm getting the error

**AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 26
     23 # Download and import Capsa
     24 # !{sys.executable} -m pip install tensorflow-probability -U
     25 get_ipython().system('{sys.executable} -m pip install capsa -U')
---> 26 import capsa

File [~/.local/lib/python3.8/site-packages/capsa/__init__.py:2](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/capsa/__init__.py:2)
      1 """ Top-level package for capsa. """
----> 2 from .base_wrapper import BaseWrapper
      3 from .risk_tensor import RiskTensor
      5 from .bias import HistogramWrapper,HistogramVAEWrapper

File [~/.local/lib/python3.8/site-packages/capsa/base_wrapper.py:3](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/capsa/base_wrapper.py:3)
      1 import tensorflow as tf
----> 3 from .utils import _get_out_dim, copy_layer
      6 class BaseWrapper(tf.keras.Model):
      7     """Base class for a metric wrapper, all of our individual metric wrappers
      8     (``MVEWrapper``, ``HistogramWrapper``, ``DropoutWrapper``, etc.) subclass it.
      9 
   (...)
     26         - changing the loss.
     27     """

File [~/.local/lib/python3.8/site-packages/capsa/utils/__init__.py:1](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/capsa/utils/__init__.py:1)
----> 1 from .utils import (
      2     # MLP,
      3     get_user_model,
      4     _get_out_dim,
      5     plt_vspan,
      6     plot_epistemic_2d,
      7     plot_loss,
      8     copy_layer,
      9     get_preds_names,
     10     plot_risk_2d,
     11     gen_calibration_plot,
     12     unpack_risk_tensor,
     13     generate_moon_data_classification
     14 )

File [~/.local/lib/python3.8/site-packages/capsa/utils/utils.py:2](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/capsa/utils/utils.py:2)
      1 import tensorflow as tf
----> 2 import tensorflow_probability as tfp
      3 from tensorflow.keras import layers
      5 import numpy as np

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/__init__.py:23](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/__init__.py:23)
     20 from tensorflow_probability import substrates
     21 # from tensorflow_probability.google import staging  # DisableOnExport
     22 # from tensorflow_probability.google import tfp_google  # DisableOnExport
---> 23 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     24 from tensorflow_probability.python.version import __version__

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/__init__.py:138](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/__init__.py:138)
    135 if _tf_loaded():
    136   # Non-lazy load of packages that register with tensorflow or keras.
    137   for pkg_name in _maybe_nonlazy_load:
--> 138     dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
    141 all_util.remove_undocumented(__name__, _lazy_load + _maybe_nonlazy_load)

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/lazy_loader.py:57](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/lazy_loader.py:57), in LazyLoader.__dir__(self)
     56 def __dir__(self):
---> 57   module = self._load()
     58   return dir(module)

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/lazy_loader.py:40](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/lazy_loader.py:40), in LazyLoader._load(self)
     38   self._on_first_access = None
     39 # Import the target module and insert it into the parent's namespace
---> 40 module = importlib.import_module(self.__name__)
     41 if self._parent_module_globals is not None:
     42   self._parent_module_globals[self._local_name] = module

File /usr/lib/python3.8/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/__init__.py:31](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/__init__.py:31)
     15 """TensorFlow Probability API-unstable package.
     16 
     17 This package contains potentially useful code which is under active development
   (...)
     27 You are welcome to try any of this out (and tell us how well it works for you!).
     28 """
     30 from tensorflow_probability.python.experimental import auto_batching
---> 31 from tensorflow_probability.python.experimental import bijectors
     32 from tensorflow_probability.python.experimental import distribute
     33 from tensorflow_probability.python.experimental import distributions

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/bijectors/__init__.py:17](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/bijectors/__init__.py:17)
      1 # Copyright 2020 The TensorFlow Probability Authors.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ============================================================================
     15 """TensorFlow Probability experimental bijectors package."""
---> 17 from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
     18 from tensorflow_probability.python.bijectors.ldj_ratio import inverse_log_det_jacobian_ratio
     19 from tensorflow_probability.python.experimental.bijectors.distribution_bijectors import make_distribution_bijector

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/__init__.py:19](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/__init__.py:19)
     15 """Bijective transformations."""
     17 # pylint: disable=unused-import,wildcard-import,line-too-long,g-importing-member
---> 19 from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
     20 from tensorflow_probability.python.bijectors.ascending import Ascending
     21 from tensorflow_probability.python.bijectors.batch_normalization import BatchNormalization

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/absolute_value.py:19](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/absolute_value.py:19)
     15 """AbsoluteValue bijector."""
     17 import tensorflow.compat.v2 as tf
---> 19 from tensorflow_probability.python.bijectors import bijector
     20 from tensorflow_probability.python.internal import assert_util
     21 from tensorflow_probability.python.internal import dtype_util

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/bijector.py:34](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/bijectors/bijector.py:34)
     32 from tensorflow_probability.python.internal import slicing
     33 from tensorflow_probability.python.internal import tensorshape_util
---> 34 from tensorflow_probability.python.math import generic as math_generic
     35 from tensorflow_probability.python.math import gradient
     37 # pylint: disable=g-direct-tensorflow-import

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/__init__.py:19](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/__init__.py:19)
     17 from tensorflow_probability.python.internal import all_util
     18 from tensorflow_probability.python.math import ode
---> 19 from tensorflow_probability.python.math import psd_kernels
     20 from tensorflow_probability.python.math.bessel import bessel_iv_ratio
     21 from tensorflow_probability.python.math.bessel import bessel_ive

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/__init__.py:18](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/__init__.py:18)
     15 """Positive-semidefinite kernels package."""
     17 from tensorflow_probability.python.internal import all_util
---> 18 from tensorflow_probability.python.math.psd_kernels.changepoint import ChangePoint
     19 from tensorflow_probability.python.math.psd_kernels.exp_sin_squared import ExpSinSquared
     20 from tensorflow_probability.python.math.psd_kernels.exponential_curve import ExponentialCurve

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/changepoint.py:28](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/changepoint.py:28)
     26 from tensorflow_probability.python.internal import prefer_static as ps
     27 from tensorflow_probability.python.internal import tensor_util
---> 28 from tensorflow_probability.python.math.psd_kernels import positive_semidefinite_kernel as psd_kernel
     29 from tensorflow_probability.python.math.psd_kernels.internal import util
     31 __all__ = ['ChangePoint']

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/positive_semidefinite_kernel.py:1217](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/positive_semidefinite_kernel.py:1217)
   1208     cls = super(_AutoCompositeTensorPsdKernelMeta, mcs).__new__(  # pylint: disable=too-many-function-args
   1209         mcs, classname, baseclasses, attrs)
   1210     return auto_composite_tensor.auto_composite_tensor(
   1211         cls,
   1212         omit_kwargs=('parameters',),
   1213         non_identifying_kwargs=('name',),
   1214         module_name='tfp.math._psdkernels')
-> 1217 class AutoCompositeTensorPsdKernel(PositiveSemidefiniteKernel,
   1218                                    auto_composite_tensor.AutoCompositeTensor,
   1219                                    metaclass=_AutoCompositeTensorPsdKernelMeta):
   1220   pass
   1223 def _flatten_summand_list(kernels):

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/positive_semidefinite_kernel.py:1210](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/math/psd_kernels/positive_semidefinite_kernel.py:1210), in _AutoCompositeTensorPsdKernelMeta.__new__(mcs, classname, baseclasses, attrs)
   1206 """Give subclasses their own type_spec, not an inherited one."""
   1208 cls = super(_AutoCompositeTensorPsdKernelMeta, mcs).__new__(  # pylint: disable=too-many-function-args
   1209     mcs, classname, baseclasses, attrs)
-> 1210 return auto_composite_tensor.auto_composite_tensor(
   1211     cls,
   1212     omit_kwargs=('parameters',),
   1213     non_identifying_kwargs=('name',),
   1214     module_name='tfp.math._psdkernels')

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/auto_composite_tensor.py:675](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/auto_composite_tensor.py:675), in auto_composite_tensor(cls, omit_kwargs, non_identifying_kwargs, module_name)
    669 # If the declared class is already a CompositeTensor subclass, we can avoid
    670 # affecting the actual type of the returned class. Otherwise, we need to
    671 # explicitly mix in the CT type, and hence create and return a newly
    672 # synthesized type.
    673 if issubclass(cls, composite_tensor.CompositeTensor):
--> 675   @type_spec_register(type_spec_name)
    676   class _AlreadyCTTypeSpec(_AutoCompositeTensorTypeSpec):
    678     @property
    679     def value_type(self):
    680       return cls

File [~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/auto_composite_tensor.py:510](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/work/mitlabs/lab3/~/.local/lib/python3.8/site-packages/tensorflow_probability/python/internal/auto_composite_tensor.py:510), in type_spec_register(name, allow_overwrite)
    491 """Decorator used to register a unique name for a TypeSpec subclass.
    492 
    493 Unlike TensorFlow's `type_spec.register`, this function allows a new
   (...)
    507   A class decorator that registers the decorated class with the given name.
    508 """
    509 # pylint: disable=protected-access
--> 510 if allow_overwrite and name in type_spec._NAME_TO_TYPE_SPEC:
    511   type_spec._TYPE_SPEC_TO_NAME.pop(
    512       type_spec._NAME_TO_TYPE_SPEC.pop(name))
    513 return type_spec.register(name)

AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'
```

**Comment by Guojyjy** [comment]
I met the same error: `AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'`, resolved by **upgrading tensorflow_probability** from 0.16.0 to the latest version (0.20.1).

**Comment by blablabLACK** [comment]
> I met the same error: `AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'`, resolved by **upgrading tensorflow_probability** from 0.16.0 to the latest version (0.20.1 ).

Upgrading TensorFlow Probability did not resolve the error. Are there any other possible solutions?

```
### conda envirionment:
tensorflow                2.13.0                   pypi_0    pypi
tensorflow-addons         0.23.0                   pypi_0    pypi
tensorflow-datasets       4.9.3                    pypi_0    pypi
tensorflow-estimator      2.13.0                   pypi_0    pypi
tensorflow-graphics       2021.12.3                pypi_0    pypi
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
tensorflow-metadata       1.16.1                   pypi_0    pypi
tensorflow-probability    0.20.1                   pypi_0    pypi
waymo-open-dataset-tf-2-12-0 1.6.7                    pypi_0    pypi
```
